matrix:
  include:
    - language: node_js
      node_js:
        - "9"

      before_script:
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update
        - sudo apt-get install yarn -y
        - cd src/client
        - yarn install

      script:
        - yarn build

    - language: java
      jdk: oraclejdk8

      sudo: required
      before_script:
        - sudo apt-get install -y maven
        - sudo apt-get install -y python-dev
        - sudo apt-get install -y libpq-dev
        - sudo service postgresql restart
        - sudo sh install/db.sh
        - cd src/spring

      script:
        - sudo sh mvnw clean package
      after_success:
        - sudo sh mvnw clean test jacoco:report coveralls:report
        
notifications:
email: false